### ISSUE TITLE
interference with cloze overlapper add-on 

### ISSUE THREAD

**Issue by galantra** [Arthur-Milchior/anki-Close-and-lose-current-input-for-sticky-fields#1]
This error occurred as I had added an [overlapping cloze ](https://ankiweb.net/shared/info/969733775) note and tried to close the add window. I couldn't close it, even after changing the note type (by the Ctrl+N shortcut).

Also, I can't close the main window. Same error.

``Error` 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.15 (6661ba8a) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\webview.py", line 322, in handler
  File "aqt\editor.py", line 351, in <lambda>
  File "C:\Users\Jo\AppData\Roaming\Anki2\addons21\1284221829\__init__.py", line 23, in afterSave
    ok = (self.editor.fieldsAreBlank(self.previousNote) or
  File "C:\Users\Jo\AppData\Roaming\Anki2\addons21\1284221829\__init__.py", line 37, in fieldsAreBlank
    if previousNote and self.model['flds'][c]['sticky']:
<class 'AttributeError'>: 'Editor' object has no attribute 'model'```

**Comment by Arthur-Milchior** [comment]
I don't know how I did miss this bug report. Sorry. Corrected
